CONTIKI_PROJECT = very-sleepy-demo

PLATFORMS_ONLY = cc26x0-cc13x0

all: $(CONTIKI_PROJECT)

#MODULES += lpm_downward
MODULES += os/net/app-layer/coap




MODULES += os/services/simple-energest
CONTIKI = ../../../..
include $(CONTIKI)/Makefile.include
